### ISSUE TITLE
Release 2.1.6 pulls alpha version of hibernate-validator

### ISSUE THREAD

**Issue by javadevmtl** [jirutka/validator-collection#20]
When including, compile 'cz.jirutka.validator:validator-collection:2.1.6', in our gradle build, it pulls 6.0.0 alpha of hibernate validator.

**Comment by jirutka** [comment]
I’ve fixed it in 7a946ba2a64f636d7eca498f8d930d4993468d21 (and 4067cc13703367416a0e54c4ecf3b4f119f08614) and released 2.2.0. It’s already available in jCenter and will be in Maven Central in few hours.
